--------------------------------------------------------
--  File created - Thursday-August-18-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ENGINES
--------------------------------------------------------

  CREATE TABLE "STEVEHARVILLE"."ENGINES" 
   (	"ENGINE_ID" NUMBER, 
	"ENG_NAME" VARCHAR2(120 BYTE), 
	"CYLINDER" NUMBER, 
	"DISP" NUMBER, 
	"CONFIG" VARCHAR2(60 BYTE), 
	"FUEL" VARCHAR2(60 BYTE), 
	"HP" NUMBER, 
	"TORQUE" NUMBER, 
	"ENG_TYPE" VARCHAR2(60 BYTE), 
	"COMPRESSOR" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENGINES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STEVEHARVILLE"."ENGINES_PK" ON "STEVEHARVILLE"."ENGINES" ("ENGINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ENGINES
--------------------------------------------------------

  ALTER TABLE "STEVEHARVILLE"."ENGINES" MODIFY ("ENGINE_ID" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."ENGINES" MODIFY ("ENG_NAME" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."ENGINES" MODIFY ("CYLINDER" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."ENGINES" MODIFY ("DISP" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."ENGINES" MODIFY ("CONFIG" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."ENGINES" MODIFY ("FUEL" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."ENGINES" MODIFY ("HP" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."ENGINES" MODIFY ("TORQUE" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."ENGINES" MODIFY ("ENG_TYPE" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."ENGINES" MODIFY ("COMPRESSOR" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."ENGINES" ADD CONSTRAINT "ENGINES_PK" PRIMARY KEY ("ENGINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
