--------------------------------------------------------
--  File created - Thursday-August-18-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAKES
--------------------------------------------------------

  drop TABLE "STEVEHARVILLE"."MAKES" ;
  CREATE TABLE "STEVEHARVILLE"."MAKES" 
   (	"MAKE_ID" NUMBER(9,0), 
	"NICENAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into STEVEHARVILLE.MAKES
SET DEFINE OFF;
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200038885,'smart');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200001769,'aston-martin');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200002038,'acura');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200464140,'alfa-romeo');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200000001,'audi');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200000081,'bmw');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200005848,'bentley');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200006659,'buick');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200001663,'cadillac');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200000404,'chevrolet');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200003644,'chrysler');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200009788,'dodge');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200033022,'fiat');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200005143,'ford');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200007302,'gmc');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200000089,'infiniti');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200003196,'jaguar');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200001510,'jeep');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200003063,'kia');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200001444,'honda');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200001398,'hyundai');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200005922,'lamborghini');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200006582,'land-rover');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200001623,'lexus');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200001777,'lincoln');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200002305,'mini');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200028029,'maserati');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200004100,'mazda');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200000130,'mercedes-benz');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200002915,'mitsubishi');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200000201,'nissan');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200000886,'porsche');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200393150,'ram');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200005044,'rolls-royce');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200006515,'scion');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200004491,'subaru');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200018920,'tesla');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200003381,'toyota');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200000238,'volkswagen');
Insert into STEVEHARVILLE.MAKES (MAKE_ID,NICENAME) values (200010382,'volvo');
--------------------------------------------------------
--  DDL for Index MAKES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STEVEHARVILLE"."MAKES_PK" ON "STEVEHARVILLE"."MAKES" ("MAKE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MAKES
--------------------------------------------------------

  ALTER TABLE "STEVEHARVILLE"."MAKES" MODIFY ("MAKE_ID" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."MAKES" MODIFY ("NICENAME" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."MAKES" ADD CONSTRAINT "MAKES_PK" PRIMARY KEY ("MAKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
