-- copyright 2016 Steve Harville
--------------------------------------------------------
--  File created - Friday-August-12-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAKES
--------------------------------------------------------

  CREATE TABLE "STEVEHARVILLE"."MAKES" 
   (	"MAKE_ID" NUMBER(9,0), 
	"NICENAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MAKES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STEVEHARVILLE"."MAKES_PK" ON "STEVEHARVILLE"."MAKES" ("MAKE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MAKES
--------------------------------------------------------

  ALTER TABLE "STEVEHARVILLE"."MAKES" MODIFY ("MAKE_ID" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."MAKES" MODIFY ("NICENAME" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."MAKES" ADD CONSTRAINT "MAKES_PK" PRIMARY KEY ("MAKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
