--------------------------------------------------------
--  File created - Thursday-August-18-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRANSMISSIONS
--------------------------------------------------------

  CREATE TABLE "STEVEHARVILLE"."TRANSMISSIONS" 
   (	"TRANS_ID" NUMBER, 
	"TRANS_NAME" VARCHAR2(60 BYTE), 
	"TTYPE" VARCHAR2(60 BYTE), 
	"SPEEDS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSMISSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STEVEHARVILLE"."TRANSMISSIONS_PK" ON "STEVEHARVILLE"."TRANSMISSIONS" ("TRANS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRANSMISSIONS
--------------------------------------------------------

  ALTER TABLE "STEVEHARVILLE"."TRANSMISSIONS" MODIFY ("TRANS_ID" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."TRANSMISSIONS" MODIFY ("TRANS_NAME" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."TRANSMISSIONS" MODIFY ("TTYPE" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."TRANSMISSIONS" MODIFY ("SPEEDS" NOT NULL ENABLE);
  ALTER TABLE "STEVEHARVILLE"."TRANSMISSIONS" ADD CONSTRAINT "TRANSMISSIONS_PK" PRIMARY KEY ("TRANS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
